/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication9;

import java.io.BufferedWriter;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Scanner;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Harshavardhan
 * Edits by Evan Hedges
 * Error with adding: the actual button is broken, you will notice that I call for the field to be cleared after add, but is never cleared
 */
public class NewJFrame extends javax.swing.JFrame {

    private static void downloadInfo(String fileName, ArrayList<Student> theList) {
        Scanner inputStream = null;
        String values = null;
        String first = null;
        String last = null;
        String address = null;         
        int i = 0;
        int temp = 0;
        StringTokenizer tokens;
        try {
            inputStream = new Scanner(new FileInputStream(fileName));
        } catch (FileNotFoundException ex) {
            System.out.println("Error opening file");
        }

        while (inputStream.hasNextLine()) {
           
            values = inputStream.nextLine();
            tokens = new StringTokenizer(values, " ");
            System.out.println(tokens.countTokens());
            if (tokens.countTokens() > 4) {
                first = tokens.nextToken();
                last = tokens.nextToken();
                address = tokens.nextToken();
                
                for(i = 0; i<=tokens.countTokens();i++)
                {
                    address += " " + tokens.nextToken();
                                        
                }
               Student tempStudent = new Student(first,last,address); 
               theList.add(tempStudent);
            } 
            
        }
    }

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        initSchools();
    }
    
    private void initSchools() {
        universities.setModel(new javax.swing.DefaultComboBoxModel(schools));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        universities = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        BDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        universities.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        universities.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                universitiesActionPerformed(evt);
            }
        });

        jLabel1.setText("University:");

        jLabel3.setText("Number of students found: ");

        jLabel4.setText("First Name:");

        jLabel5.setText("Last Name:");

        jLabel6.setText("Address:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Add");

        jButton2.setText("Next");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        BDelete.setText("Delete");
        BDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(universities, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jTextField2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(BDelete))
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(universities, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(8, 8, 8)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*Drop down menu*/
    private void universitiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_universitiesActionPerformed
        // TODO add your handling code here:
        if(universities.getSelectedItem().toString().matches("McMaster University"))
        {
            tempArray = (ArrayList<Student>)hashSchools.get("McMaster").clone();
            schoolFile = "mcmaster.txt"; 
        }
        else if(universities.getSelectedItem().toString().matches("University of Guelph"))
        {
            tempArray = (ArrayList<Student>)hashSchools.get("Guelph").clone();
            schoolFile = "uguelph.txt"; 
        }
        else if(universities.getSelectedItem().toString().matches("University of Toronto"))
        {
            tempArray = (ArrayList<Student>)hashSchools.get("Toronto").clone();
            schoolFile = "utoronto.txt"; 
        }
        
        jTextField1.setText("");
        jTextField2.setText("");
        jTextArea1.setText("");
    }//GEN-LAST:event_universitiesActionPerformed
/*Delete button*/
    private void BDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDeleteActionPerformed
        // TODO add your handling code here:
        
        int i = 0;
         FileWriter fileOut = null;
        try {
            fileOut = new FileWriter(schoolFile);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(fileOut !=null)
        {
            try { 
                fileOut.write("");
            } catch (IOException ex) {
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
       
        for (i = 0;i<tempArray.size(); i++)
        {
            if(tempArray.get(i).firstName.matches(jTextField1.getText())  && tempArray.get(i).lastName.matches(jTextField2.getText()))
            {
            tempArray.remove(i);
            }
            else
            {                
                PrintWriter outputStream = null;
        //Use FileWriter to write to file
        //Use BufferedWriter to improve write performance by delayed buffered writes
        System.out.println(jTextField1.getText());
        PrintWriter catalog;
        try {
            catalog = new PrintWriter(new BufferedWriter(new FileWriter(schoolFile, true)));

            //write code to print info to the file in the format:\
            catalog.println(tempArray.get(i).firstName+" "+tempArray.get(i).lastName+" "+tempArray.get(i).address);
            
            //<ItemName> by <itemCreator> for <Price>

            catalog.close();
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
            }
        }
        
        jTextField1.setText("");
        jTextField2.setText("");
        jTextArea1.setText("");
        }
        jTextField1.setText("");
        jTextField2.setText("");
        jTextArea1.setText("");

    }//GEN-LAST:event_BDeleteActionPerformed

    /*Next button*/
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here  
        
        if(index > tempArray.size()-1)
        {
            index = 0;
        }
        Student temp = tempArray.get(index);
        jTextField1.setText(temp.firstName);
        jTextField2.setText(temp.lastName);
        jTextArea1.setText(temp.address);
        index ++;
        
    }//GEN-LAST:event_jButton2ActionPerformed
 /*add*/
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

        //Use the PrintWriter to get the familiar println syntax
        PrintWriter outputStream = null;
        //Use FileWriter to write to file
        //Use BufferedWriter to improve write performance by delayed buffered writes
        System.out.println(jTextField1.getText());
        PrintWriter catalog;
        try {
            catalog = new PrintWriter(new BufferedWriter(new FileWriter(schoolFile, true)));

            //write code to print info to the file in the format:\
            catalog.println(jTextField1.getText()+" " + jTextField2.getText()+" "+jTextArea1.getText());
            
            //<ItemName> by <itemCreator> for <Price>

            catalog.close();
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jTextField1.setText("");
        jTextField2.setText("");
        jTextArea1.setText("");
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    static HashMap <String,ArrayList<Student>> hashSchools = new HashMap<String,ArrayList<Student>>();
    static ArrayList <Student> Guelph = new ArrayList<Student>();
    static ArrayList <Student> McMaster = new ArrayList<Student>();
    static ArrayList <Student> Toronto = new ArrayList<Student>(); 
    static ArrayList <Student> tempArray = new ArrayList<Student>();
    String schoolFile = "mcmaster.txt"; 
    int index = 0;
        
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        
        Scanner input = new Scanner(System.in);
        String fileName = null;
        String inputFile = null;
        String command;

        Boolean savedData = true;
        int i = 0;

        fileName = "uguelph.txt";       
        downloadInfo(fileName,Guelph);
        fileName = "mcmaster.txt";
        downloadInfo(fileName,McMaster);
        fileName = "utoronto.txt";
        downloadInfo(fileName,Toronto);
        
        /* Create and display the form */
       
        hashSchools.put("Guelph", Guelph);
        hashSchools.put("McMaster", McMaster);
        hashSchools.put("Toronto", Toronto);
        tempArray = (ArrayList<Student>)hashSchools.get("McMaster").clone();

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    private String[] schools = {"McMaster University", "University of Guelph", "University of Toronto"};
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BDelete;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JComboBox universities;
    // End of variables declaration//GEN-END:variables
    
    
}
