SELECT INDIVIDUAL.id,INDIVIDUAL.name,INDIVIDUAL.birthday,ADDRESS.address,FILE.file_name,FILE.num_props
FROM INDIVIDUAL
INNER JOIN ADDRESS 
ON INDIVIDUAL.address = ADDRESS.id
INNER JOIN FILE 
ON INDIVIDUAL.source_file = FILE.id
ORDER BY INDIVIDUAL.name ASC;

SELECT INDIVIDUAL.id,INDIVIDUAL.name,INDIVIDUAL.birthday,ADDRESS.address,FILE.file_name,FILE.num_props
FROM INDIVIDUAL
INNER JOIN ADDRESS 
ON INDIVIDUAL.address = ADDRESS.id
INNER JOIN FILE 
ON INDIVIDUAL.source_file = FILE.id
ORDER BY INDIVIDUAL.birthday ASC;

SELECT INDIVIDUAL.id,INDIVIDUAL.name,INDIVIDUAL.birthday,ADDRESS.address,FILE.file_name,FILE.num_props
FROM INDIVIDUAL
INNER JOIN ADDRESS 
ON INDIVIDUAL.address = ADDRESS.id
INNER JOIN FILE 
ON INDIVIDUAL.source_file = FILE.id
WHERE ADDRESS.address = 'Westeros';

SELECT INDIVIDUAL.id,INDIVIDUAL.name,FILE.num_props
FROM INDIVIDUAL
INNER JOIN ADDRESS 
ON INDIVIDUAL.address = ADDRESS.id
INNER JOIN FILE 
ON INDIVIDUAL.source_file = FILE.id
WHERE INDIVIDUAL.name = 'John Snow';

SELECT INDIVIDUAL.id,INDIVIDUAL.name,INDIVIDUAL.birthday,ADDRESS.address,FILE.file_name,FILE.num_props
FROM INDIVIDUAL
INNER JOIN ADDRESS 
ON INDIVIDUAL.address = ADDRESS.id
INNER JOIN FILE 
ON INDIVIDUAL.source_file = FILE.id
WHERE ADDRESS.address = 'Westeros' AND INDIVIDUAL.birthday > '1970-01-01' AND INDIVIDUAL.birthday < '2005-01-01';

SELECT INDIVIDUAL.id,INDIVIDUAL.name,INDIVIDUAL.birthday,ADDRESS.address,FILE.file_name,FILE.num_props
FROM INDIVIDUAL
INNER JOIN ADDRESS 
ON INDIVIDUAL.address = ADDRESS.id
INNER JOIN FILE 
ON INDIVIDUAL.source_file = FILE.id
WHERE FILE.file_name = 'Stark.vcf';

SELECT INDIVIDUAL.id,INDIVIDUAL.name,INDIVIDUAL.birthday,ADDRESS.address,FILE.file_name,FILE.num_props
FROM INDIVIDUAL
INNER JOIN ADDRESS 
ON INDIVIDUAL.address = ADDRESS.id
INNER JOIN FILE 
ON INDIVIDUAL.source_file = FILE.id
WHERE FILE.num_props > 5;


